<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [4]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [5]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [7]:
model.coef_

array([135.78767123])

In [8]:
model.intercept_

180616.43835616432

In [9]:
model.predict([[5000]])

d:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [10]:
import pickle

In [11]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

<h4 style='color:purple'>Load Saved Model</h4>

In [12]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [13]:
mp.coef_

array([135.78767123])

In [14]:
mp.intercept_

180616.43835616432

In [15]:
mp.predict([[5000]])

d:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [16]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (d:\Anaconda\lib\site-packages\sklearn\externals\__init__.py)

In [ ]:
joblib.dump(model, 'model_joblib')

['model_joblib']

<h4 style='color:purple'>Load Saved Model</h4>

In [ ]:
mj = joblib.load('model_joblib')

In [ ]:
mj.coef_

array([135.78767123])

In [ ]:
mj.intercept_

180616.43835616432

In [ ]:
mj.predict([[5000]])

array([859554.79452055])